package main;

import app.server.Server;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class SrvFrm extends javax.swing.JFrame {

    private Server server;
    
    /**
     * Creates new form SrvFrm
     */
    public SrvFrm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        this.initList();
        
        this.statusLbl.setText("Ugaseno");
        this.statusLbl.setForeground(Color.red);
    }
    
    private void initList()
    {
        this.loggedInUsersListTable.setModel(new BrokerTableModel(new ArrayList<>()));
    }
    
    public void refreshList()
    {
        this.loggedInUsersListTable.setModel(
                new BrokerTableModel(
                        this.server.getLoggedInBrokers()
                )
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startServerButton = new javax.swing.JButton();
        statusLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loggedInUsersListTable = new javax.swing.JTable();
        dbConfigButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startServerButton.setText("Pokreni");
        startServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startServerButtonActionPerformed(evt);
            }
        });

        statusLbl.setText("Nije pokrenuto");

        loggedInUsersListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(loggedInUsersListTable);

        dbConfigButton.setText("Konfiguracija baze ");
        dbConfigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbConfigButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startServerButton)
                        .addGap(18, 18, 18)
                        .addComponent(statusLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dbConfigButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startServerButton)
                    .addComponent(statusLbl)
                    .addComponent(dbConfigButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerButtonActionPerformed
        if(this.server == null) {
            this.server = new Server(this);
            this.server.start();
            this.statusLbl.setText("Pokrenuto");
            this.statusLbl.setForeground(Color.green);
            this.startServerButton.setText("Ugasi");
            this.dbConfigButton.setEnabled(false);
        } else {
            try {
                this.server.stopServer();
                this.server = null;
                this.statusLbl.setText("Ugaseno");
                this.statusLbl.setForeground(Color.red);
                this.startServerButton.setText("Pokreni");
                this.dbConfigButton.setEnabled(true);
            } catch (SQLException | IOException ex) {
                JOptionPane.showMessageDialog(this, "Greska prilikom gasenja servera", "", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(SrvFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_startServerButtonActionPerformed

    private void dbConfigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbConfigButtonActionPerformed
        if(this.server == null) {
            (new DBConfigForm(this, false)).setVisible(true);
        }
    }//GEN-LAST:event_dbConfigButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbConfigButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loggedInUsersListTable;
    private javax.swing.JButton startServerButton;
    private javax.swing.JLabel statusLbl;
    // End of variables declaration//GEN-END:variables
}
