/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controllers.Communication;
import domain.Client;
import domain.Broker;
import domain.Deal;
import domain.Product;
import domain.ProductFeature;
import enums.DealStatus;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kredium
 */
public class DealCreateForm extends javax.swing.JDialog {

    private Deal deal;
    
    /**
     * Creates new form DealCreateForm
     */
    public DealCreateForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        initProductsTable();
        initDealStatusesDropdown();
        initClientsDropdown();
        initBrokersDropdown();
        initProductFeaturesTable();
    }
    
    public void setDeal(Deal deal)
    {
        this.deal = deal;
        this.clientCB.setSelectedItem(deal.getClient());
        this.brokerCB.setSelectedItem(deal.getBroker());
        this.dealValue.setText(deal.getDealValue().toString());
        this.dealStatusCB.setSelectedItem(deal.getDealStatus());
        this.descTxt.setText(deal.getDescription());
        
        ProductTableModel ptm = (ProductTableModel) this.productsTable.getModel();
        int i = ptm.indexOf(deal.getProduct());
        
        if(i >= 0) {
            this.productsTable.setRowSelectionInterval(i, i);
        }
    }
    
    private void initProductFeaturesTable()
    {
        this.pfsTable.setModel(
                new ProductFeatureTableModel()
        );
    }
    
    private void initDealStatusesDropdown()
    {
        this.dealStatusCB.setModel(
                new DefaultComboBoxModel(
                        DealStatus.values()
                )
        );
    }
    
    private void initClientsDropdown()
    {
        try {
            this.clientCB.setModel(
                    new DefaultComboBoxModel(
                            Communication.getInstance().getAllClients().toArray()
                    )
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot load clients");
            Logger.getLogger(DealCreateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void initBrokersDropdown()
    {
        try {
            this.brokerCB.setModel(
                    new DefaultComboBoxModel(
                            Communication.getInstance().getAllBrokers().toArray()
                    )
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot load brokers");
            Logger.getLogger(DealCreateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void initProductsTable()
    {
        try {
            this.productsTable.setModel(
                    new ProductTableModel(
                            Communication.getInstance().getAllProducts()
                    )
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cannot load products");
            Logger.getLogger(DealCreateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        clientCB = new javax.swing.JComboBox();
        brokerCB = new javax.swing.JComboBox<>();
        dealValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dealStatusCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTxt = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        deleteProductBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addPfs = new javax.swing.JButton();
        removePfs = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        npTitle = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        pfsTable = new javax.swing.JTable();
        saveDealbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Klijent:");

        jLabel1.setText("Vrednost:");

        jLabel2.setText("Status:");

        descTxt.setColumns(20);
        descTxt.setRows(5);
        jScrollPane1.setViewportView(descTxt);

        jLabel3.setText("Opis");

        jLabel4.setText("Prodavac:");

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(productsTable);

        jLabel6.setText("Izaberi proizvod:");

        deleteProductBtn.setText("Obrisi");
        deleteProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Naziv proizvoda:");

        jLabel9.setText("Karakteristike:");

        addPfs.setText("+");
        addPfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPfsActionPerformed(evt);
            }
        });

        removePfs.setText("-");
        removePfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePfsActionPerformed(evt);
            }
        });

        jLabel7.setText("ILI - KREIRAJ NOVI PROIZVOD");

        pfsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(pfsTable);

        saveDealbtn.setText("SACUVAJ PRODAJNU SANSU");
        saveDealbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDealbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clientCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(brokerCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dealValue)
                                            .addComponent(dealStatusCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1)))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addComponent(deleteProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addPfs, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(removePfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(npTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(saveDealbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clientCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brokerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dealValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(dealStatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteProductBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(npTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addPfs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePfs)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(saveDealbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBtnActionPerformed
        int i = this.productsTable.getSelectedRow();
        ProductTableModel ptm = (ProductTableModel) this.productsTable.getModel();
        
        if(i >= 0) {
            Product product = ptm.getProductAt(i);
            try {
                Communication.getInstance().deleteProduct(product);
                ptm.removeProductAt(i);
                this.productsTable.setModel(ptm);
                JOptionPane.showMessageDialog(this, "Product deleted");
            } catch (Exception ex) {
                Logger.getLogger(ClientViewForm.class.getName()).log(Level.SEVERE, null, ex);
                
                JOptionPane.showMessageDialog(this, "Product not deleted");
            }
        }
    }//GEN-LAST:event_deleteProductBtnActionPerformed

    private void saveDealbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDealbtnActionPerformed
        Client client = (Client) this.clientCB.getSelectedItem();
        Broker broker = (Broker) this.brokerCB.getSelectedItem();
        int selectedProductRow = this.productsTable.getSelectedRow();
        
        Product product;
        if(selectedProductRow >= 0) {
            product = ((ProductTableModel) this.productsTable.getModel())
                .getProductAt(
                        this.productsTable.getSelectedRow()
                );
        } else {
            product = new Product();
            product.setTitle(npTitle.getText());
            
            ProductFeatureTableModel pftm = (ProductFeatureTableModel) this.pfsTable.getModel();
            product.setProductFeatures(pftm.getFeatures());
        }
        
        Double value = Double.valueOf(dealValue.getText());
        DealStatus status = (DealStatus) dealStatusCB.getSelectedItem();
        String description = descTxt.getText();
        
        Deal deal = new Deal();
        deal.setClient(client);
        deal.setBroker(broker);
        deal.setProduct(product);
        deal.setDealValue(value);
        deal.setDealStatus(status);
        deal.setDescription(description);
        
        try {
            Communication.getInstance().saveDeal(deal);
            JOptionPane.showMessageDialog(this, "Deal saved");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Deal not saved");
            Logger.getLogger(DealCreateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveDealbtnActionPerformed

    private void addPfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPfsActionPerformed
        ProductFeatureTableModel pftm = (ProductFeatureTableModel) this.pfsTable.getModel();
        pftm.addFeature(new ProductFeature());
        this.pfsTable.setModel(pftm);
    }//GEN-LAST:event_addPfsActionPerformed

    private void removePfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePfsActionPerformed
        int i = this.pfsTable.getSelectedRow();
        ProductFeatureTableModel pftm = (ProductFeatureTableModel) this.pfsTable.getModel();
        
        if(i >= 0) {
            pftm.removeFeatureAt(i);
            this.pfsTable.setModel(pftm);
        }
    }//GEN-LAST:event_removePfsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPfs;
    private javax.swing.JComboBox<String> brokerCB;
    private javax.swing.JComboBox clientCB;
    private javax.swing.JComboBox<String> dealStatusCB;
    private javax.swing.JTextField dealValue;
    private javax.swing.JButton deleteProductBtn;
    private javax.swing.JTextArea descTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField npTitle;
    private javax.swing.JTable pfsTable;
    private javax.swing.JTable productsTable;
    private javax.swing.JButton removePfs;
    private javax.swing.JButton saveDealbtn;
    // End of variables declaration//GEN-END:variables
}
